server:
  port: 8087

spring:
  application:
    name: online-resource-hub
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/online_resource_hub?createDatabaseIfNotExist=true
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false



  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/OnlineResourceHub
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


keycloak:
  token-uri: http://localhost:7080/realms/OnlineResourceHub/protocol/openid-connect/token
  grant-type: password
  client-id: OnlineResourceHub
  admin-client-id: admin-cli
  admin-username: admin
  admin-password: admin
  realm-base-url: http://localhost:7080/realms/OnlineResourceHub
  masterUrl: http://localhost:7080/realms/master/protocol/openid-connect/token
  client-user-uri: http://localhost:7080/realms/OnlineResourceHub/users
  client-uuid: 60cbfeb0-14a7-484c-863d-45ab7c370aee


notifications:
  service-url: http://localhost:8082/notifications/send-notification
  jwt:
    auth:
      converter:
        resource-id: OnlineResourceHub
        principal-attribute: preferred_username
api-urls:
  frontend-login-link: http://44.196.149.62:4200
  auth-service: http://localhost:8078
#eureka:
#  instance:server:
#  port: 8087
#
#spring:
#  application:
#    name: keycloak-auth-service
#  datasource:
#     driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#     url: jdbc:sqlserver://52.4.172.195;instance=;DatabaseName=EpayDatabase2;trustServerCertificate=true;
#     username: sa
#     password: "%$Afro123"
#  jpa:
#      hibernate:
#        ddl-auto: update
#      show-sql: false
#
#
#
#  servlet:
#    multipart:
#      max-file-size: 500MB
#      max-request-size: 500MB
#
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:7080/realms/OnlineResourceHub
#          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
#
#
#keycloak:
#  token-uri: http://localhost:7080/realms/OnlineResourceHub/protocol/openid-connect/token
#  grant-type: password
#  client-id: OnlineResourceHub
#  admin-client-id: admin-cli
#  admin-username: admin
#  admin-password: admin
#  realm-base-url: http://localhost:7080/realms/OnlineResourceHub
#  masterUrl: http://localhost:7080/realms/master/protocol/openid-connect/token
#  client-user-uri: http://localhost:7080/realms/OnlineResourceHub/users
#  client-uuid: 60cbfeb0-14a7-484c-863d-45ab7c370aee
#
#
#notifications:
#  service-url: http://localhost:8082/notifications/send-notification
#  jwt:
#    auth:
#      converter:
#        resource-id: OnlineResourceHub
#        principal-attribute: preferred_username
#api-urls:
#  frontend-login-link: http://44.196.149.62:4200
#  auth-service: http://localhost:8078
##eureka:
##  instance:
##    prefer-ip-address: true
##  client:
##    registerWithEureka: true
##    fetchRegistry: true
##    serviceUrl:
##      defaultZone: http://44.196.149.62:8445/eureka/
#    prefer-ip-address: true
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://44.196.149.62:8445/eureka/