server:
  port: 8087

spring:
  datasource:
    url: jdbc:sqlserver://192.168.10.187;databaseName=student;trustServerCertificate=true;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: "%$Afro123"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://44.196.149.62:8080/realms/InstalipaGateway
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


keycloak:
  token-uri: http://44.196.149.62:8080/realms/InstalipaGateway/protocol/openid-connect/token
  grant-type: password
  client-id: InstalipaGateway
  admin-client-id: admin-cli
  admin-username: admin
  admin-password: admin
  realm-base-url: http://44.196.149.62:8080/admin/realms/InstalipaGateway
  masterUrl: http://44.196.149.62:8080/realms/master/protocol/openid-connect/token
  client-user-uri: http://44.196.149.62:8080/admin/realms/InstalipaGateway/users
  client-uuid: 60cbfeb0-14a7-484c-863d-45ab7c370aee


notifications:
  service-url: http://localhost:8082/notifications/send-notification
  jwt:
    auth:
      converter:
        resource-id: InstalipaGateway
        principal-attribute: preferred_username
api-urls:
  frontend-login-link: http://44.196.149.62:4200
  auth-service: http://localhost:8078
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://44.196.149.62:8445/eureka/